---
title: Block embed
---

## Also known as block embedding allows a portion of a page to be displayed within another. Edits made to the embedded content are also made in the referenced content.
### Create a block embed by :
#### Typing `{{{embed ((block id))}}}`
##
#+BEGIN_TIP
- Block id's can be generated by right-clicking the bullet point next to a block and selecting 'copy block ref'
- Auto-completion is available for blocks and will automatically generate and insert a block id
#+END_TIP
